language: ruby
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
#script:
#  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script: 
    - rake db:migrate
    - rake db:seed
