admin:  [ "admin@gameofthecalf.fr", "olivier.sallou@irisa.fr" ]

languages: [ "en", "fr" ]

max_levels: 8

default_bulls: 5
default_cows: 50

max_bulls: 5
max_cows: 10

market_max_user: 2
market_max_final: 5

credit_default: 1000
